<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Resources\invoice-to-pdf.html" />
      <Content Include="Resources\invoice-to-pdf.html">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Handlebars.Net" Version="2.1.6" />
      <PackageReference Include="PuppeteerSharp" Version="25.1.2" />
    </ItemGroup>

</Project>
